#!/bin/bash
#
# Copyright (C) 2020-2021 by UsergeTeam

. init/proc.sh

declare -ir usr1=138
declare -r cmd='. init/init.sh; runUserge "$@"'

run() {
    reInitProc
    bash -c "$cmd" $0 "$@" &
    setProc $!
    waitProc
    test $? -eq $usr1 && run "$@"
}

run "$@"
